### ISSUE TITLE
Which algorithm/-s does it use ?

### ISSUE THREAD

**Issue by irvnriir** [espresso3389/genrandom-vscode#3]

**Comment by espresso3389** [comment]
Until 0.0.6, it mistakenly uses `crypto.pseudoRandomBytes` as entropy source. I've just replaced it with `crypto.randomBytes` for better entropy quality.

**Comment by irvnriir** [comment]
Just by the way, this function (-s) comes to Electron: from Node.js; and is a call to OpenSSL one which uses and changes/alters OS's CSRNG, which on Windows is `Win32\BCryptGenRandom` which's algorithm is undisclosed .
